/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TankRouteImport } from './routes/tank'
import { Route as TableRouteImport } from './routes/table'
import { Route as IndexRouteImport } from './routes/index'

const TankRoute = TankRouteImport.update({
  id: '/tank',
  path: '/tank',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/tank': typeof TankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/tank': typeof TankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/tank': typeof TankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/table' | '/tank'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table' | '/tank'
  id: '__root__' | '/' | '/table' | '/tank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRoute: typeof TableRoute
  TankRoute: typeof TankRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tank': {
      id: '/tank'
      path: '/tank'
      fullPath: '/tank'
      preLoaderRoute: typeof TankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRoute: TableRoute,
  TankRoute: TankRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
