/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TankRouteImport } from './routes/{-$locale}/tank'
import { Route as Char123LocaleChar125TableRouteImport } from './routes/{-$locale}/table'
import { Route as Char123LocaleChar125JournalRouteImport } from './routes/{-$locale}/journal'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TankRoute =
  Char123LocaleChar125TankRouteImport.update({
    id: '/tank',
    path: '/tank',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TableRoute =
  Char123LocaleChar125TableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125JournalRoute =
  Char123LocaleChar125JournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/journal': typeof Char123LocaleChar125JournalRoute
  '/{-$locale}/table': typeof Char123LocaleChar125TableRoute
  '/{-$locale}/tank': typeof Char123LocaleChar125TankRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/journal': typeof Char123LocaleChar125JournalRoute
  '/{-$locale}/table': typeof Char123LocaleChar125TableRoute
  '/{-$locale}/tank': typeof Char123LocaleChar125TankRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/journal': typeof Char123LocaleChar125JournalRoute
  '/{-$locale}/table': typeof Char123LocaleChar125TableRoute
  '/{-$locale}/tank': typeof Char123LocaleChar125TankRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/journal'
    | '/{-$locale}/table'
    | '/{-$locale}/tank'
    | '/{-$locale}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/journal'
    | '/{-$locale}/table'
    | '/{-$locale}/tank'
    | '/{-$locale}'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/journal'
    | '/{-$locale}/table'
    | '/{-$locale}/tank'
    | '/{-$locale}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/tank': {
      id: '/{-$locale}/tank'
      path: '/tank'
      fullPath: '/{-$locale}/tank'
      preLoaderRoute: typeof Char123LocaleChar125TankRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/table': {
      id: '/{-$locale}/table'
      path: '/table'
      fullPath: '/{-$locale}/table'
      preLoaderRoute: typeof Char123LocaleChar125TableRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/journal': {
      id: '/{-$locale}/journal'
      path: '/journal'
      fullPath: '/{-$locale}/journal'
      preLoaderRoute: typeof Char123LocaleChar125JournalRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125JournalRoute: typeof Char123LocaleChar125JournalRoute
  Char123LocaleChar125TableRoute: typeof Char123LocaleChar125TableRoute
  Char123LocaleChar125TankRoute: typeof Char123LocaleChar125TankRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125JournalRoute: Char123LocaleChar125JournalRoute,
    Char123LocaleChar125TableRoute: Char123LocaleChar125TableRoute,
    Char123LocaleChar125TankRoute: Char123LocaleChar125TankRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
